### ISSUE TITLE
"721Staging" Branch Bugs / Features Request

### ISSUE THREAD

**Issue by simplemachine92** [moonshotcollective/fund.party#3]
Creating this to document & track front-end development.

**Project Collection View** (Home.jsx, PGCard.jsx, Funding.jsx, Checkout.jsx) :

- [ ] Cards don’t resize properly
- [ ] Project collection loading is slow && has no loading indicator
- [ ] We need a different method for getting a preview image (lines #35, 36, 38, 39, 50, in PGCard)
- [ ] Cart disappears on redirect w/ antd Menu
- [ ] Duplicate Items can be added to cart

**TokenDetails / Creation Modal:** (DeployModal.jsx, TokenDetails.jsx, Deployer.jsx)

- [ ] CID submission has no loading indicator
- [ ] Token inflation rate: Should be in percentages vs entered as “1030”, e.g currently 1030 = 3%.

**Features:**

- [ ] Search / Sort Project by name, type, # minted?
- [ ] Create / Explore / Fund “Flows” - I’ll create a landing page that pushes Users toward the correct initial view based on their interests.
- [ ] "View" Page should have a preview image, description, maybe social media / official website links.

**Comment by ironsoul0** [comment]
Pushing a new commit that resolves the following tasks:

> Current Progress in terms of tasks
> 
> **Project Collection View** (Home.jsx, PGCard.jsx, Funding.jsx, Checkout.jsx) :
> 
> * [x]  Cards don’t resize properly
> * [x]  Project collection loading is slow && has no loading indicator
> * [x]  We need a different method for getting a preview image (lines #35, 36, 38, 39, 50, in PGCard)
> * [x]  Cart disappears on redirect w/ antd Menu
> * [x]  Duplicate Items can be added to cart
> 
> **TokenDetails / Creation Modal:** (DeployModal.jsx, TokenDetails.jsx, Deployer.jsx)
> 
> * [x]  CID submission has no loading indicator
> * [x]  Token inflation rate: Should be in percentages vs entered as “1030”, e.g currently 1030 = 3%.
> 
> **Features:**
> 
> * [ ]  Search / Sort Project by name, type, # minted?
> * [ ]  Create / Explore / Fund “Flows” - I’ll create a landing page that pushes Users toward the correct initial view based on their interests.
> * [ ]  "View" Page should have a preview image, description, maybe social media / official website links.

<img width="1668" alt="Screen Shot 2022-01-22 at 15 45 47" src="https://user-images.githubusercontent.com/31582693/150633533-6c7b10b7-f895-4377-affc-e93b8bbf5991.png">
